/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    fonts: Font;
    media: Media;
    'marketing-copy': MarketingCopy;
    pages: Page;
    themes: Theme;
    templates: Template;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    fonts: FontsSelect<false> | FontsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'marketing-copy': MarketingCopySelect<false> | MarketingCopySelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'owner' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Font library. Add a font here, then select it from the dropdown in Themes > Typography. Preview-site injects the stylesheet automatically at runtime.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fonts".
 */
export interface Font {
  id: number;
  /**
   * CSS font-family name. Must match exactly what the stylesheet declares, e.g. "Fraunces".
   */
  family: string;
  /**
   * Stylesheet URL (Google Fonts etc.). Leave empty for system fonts like Georgia or Arial — they're already installed on every device.
   */
  sourceUrl?: string | null;
  /**
   * Fallback stack, e.g. "Georgia, serif". Both family and fallback are joined into the CSS font-family value.
   */
  fallback: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what the image shows -- read aloud by screen readers.
   */
  alt: string;
  /**
   * Helps filter the media library by where an image is used.
   */
  tag?: ('hero' | 'icon' | 'background' | 'illustration' | 'logo' | 'other') | null;
  /**
   * Optional: where on the site this is used, for future reference.
   */
  usageNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Text strings used in marketing pages. "Key" identifies where a string is used.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-copy".
 */
export interface MarketingCopy {
  id: number;
  /**
   * Must match a real RootLink i18n key, e.g. "home.hero_title" -- this is what gets overridden on the live site. Do not change once in use.
   */
  key: string;
  /**
   * Optional: which page/section this belongs to, for filtering, e.g. "Homepage".
   */
  page?: string | null;
  value: string;
  locale?: ('en' | 'pt') | null;
  /**
   * Optional context for other editors, e.g. "Shown only to logged-out visitors".
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Site pages. Each page has a URL path (slug) and is composed of blocks. Parent pages create the site tree.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Display name, e.g. "Homepage" or "About Us".
   */
  title: string;
  /**
   * URL path, e.g. "/" for homepage, "/about" for About page. Must start with /.
   */
  slug: string;
  /**
   * Parent page — leave empty for top-level pages. Creates the site tree.
   */
  parent?: (number | null) | Page;
  status: 'draft' | 'published';
  /**
   * Sort order within the same level of the tree. Lower = first.
   */
  order?: number | null;
  /**
   * Drag to reorder. The structure of this page, top to bottom.
   */
  blocks?:
    | (
        | {
            /**
             * Small label above the headline, e.g. "New" or a section name. Optional.
             */
            eyebrow?: string | null;
            headline: string;
            subhead?: string | null;
            image?: (number | null) | Media;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            body: string;
            alignment?: ('left' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
        | {
            image: number | Media;
            imagePosition?: ('left' | 'right') | null;
            heading?: string | null;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageWithText';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel: string;
            buttonHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Design tokens: color palette, typography, spacing. Multiple themes can exist; mark one active per site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  /**
   * e.g. "RootLink Default"
   */
  name: string;
  /**
   * The active theme is the one currently live on the site.
   */
  isActive?: boolean | null;
  palette: {
    primary: {
      seed: string;
      scale: {
        s50: string;
        s100: string;
        s200: string;
        s300: string;
        s400: string;
        s500: string;
        s600: string;
        s700: string;
        s800: string;
        s900: string;
      };
    };
    earth: {
      seed: string;
      scale: {
        s50: string;
        s100: string;
        s200: string;
        s300: string;
        s400: string;
        s500: string;
        s600: string;
        s700: string;
        s800: string;
        s900: string;
      };
    };
    rust: {
      seed: string;
      scale: {
        s50: string;
        s100: string;
        s200: string;
        s300: string;
        s400: string;
        s500: string;
        s600: string;
        s700: string;
        s800: string;
        s900: string;
      };
    };
    cream: string;
  };
  /**
   * Body/serif font. Pick from the Fonts library.
   */
  fontBody?: (number | null) | Font;
  /**
   * Display/heading font. Pick from the Fonts library.
   */
  fontDisplay?: (number | null) | Font;
  /**
   * Monospace font for technical data / IDs.
   */
  fontMono?: (number | null) | Font;
  scale?:
    | {
        level: 'h1' | 'h2' | 'h3' | 'body' | 'small' | 'mono';
        sizePx: number;
        weight: '400' | '500' | '600' | '700';
        lineHeight: number;
        id?: string | null;
      }[]
    | null;
  spacing?:
    | {
        /**
         * e.g. sm, md, lg
         */
        token: string;
        valuePx: number;
        id?: string | null;
      }[]
    | null;
  radii?: {
    sm?: number | null;
    md?: number | null;
    lg?: number | null;
    xl2?: number | null;
    full?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable page layouts built from blocks. Reorder, add, or remove blocks below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  /**
   * Internal name, e.g. "Homepage" or "Donate landing page".
   */
  name: string;
  /**
   * Optional: what this template is for / where it is used.
   */
  description?: string | null;
  /**
   * Drag to reorder. This defines the structure of the page, top to bottom.
   */
  blocks?:
    | (
        | {
            /**
             * Small label above the headline, e.g. "New" or a section name. Optional.
             */
            eyebrow?: string | null;
            headline: string;
            subhead?: string | null;
            image?: (number | null) | Media;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            body: string;
            alignment?: ('left' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
        | {
            image: number | Media;
            imagePosition?: ('left' | 'right') | null;
            heading?: string | null;
            body: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageWithText';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel: string;
            buttonHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'fonts';
        value: number | Font;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'marketing-copy';
        value: number | MarketingCopy;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'themes';
        value: number | Theme;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fonts_select".
 */
export interface FontsSelect<T extends boolean = true> {
  family?: T;
  sourceUrl?: T;
  fallback?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tag?: T;
  usageNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marketing-copy_select".
 */
export interface MarketingCopySelect<T extends boolean = true> {
  key?: T;
  page?: T;
  value?: T;
  locale?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  status?: T;
  order?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subhead?: T;
              image?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textSection?:
          | T
          | {
              heading?: T;
              body?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        imageWithText?:
          | T
          | {
              image?: T;
              imagePosition?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  name?: T;
  isActive?: T;
  palette?:
    | T
    | {
        primary?:
          | T
          | {
              seed?: T;
              scale?:
                | T
                | {
                    s50?: T;
                    s100?: T;
                    s200?: T;
                    s300?: T;
                    s400?: T;
                    s500?: T;
                    s600?: T;
                    s700?: T;
                    s800?: T;
                    s900?: T;
                  };
            };
        earth?:
          | T
          | {
              seed?: T;
              scale?:
                | T
                | {
                    s50?: T;
                    s100?: T;
                    s200?: T;
                    s300?: T;
                    s400?: T;
                    s500?: T;
                    s600?: T;
                    s700?: T;
                    s800?: T;
                    s900?: T;
                  };
            };
        rust?:
          | T
          | {
              seed?: T;
              scale?:
                | T
                | {
                    s50?: T;
                    s100?: T;
                    s200?: T;
                    s300?: T;
                    s400?: T;
                    s500?: T;
                    s600?: T;
                    s700?: T;
                    s800?: T;
                    s900?: T;
                  };
            };
        cream?: T;
      };
  fontBody?: T;
  fontDisplay?: T;
  fontMono?: T;
  scale?:
    | T
    | {
        level?: T;
        sizePx?: T;
        weight?: T;
        lineHeight?: T;
        id?: T;
      };
  spacing?:
    | T
    | {
        token?: T;
        valuePx?: T;
        id?: T;
      };
  radii?:
    | T
    | {
        sm?: T;
        md?: T;
        lg?: T;
        xl2?: T;
        full?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              subhead?: T;
              image?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textSection?:
          | T
          | {
              heading?: T;
              body?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        imageWithText?:
          | T
          | {
              image?: T;
              imagePosition?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}